### PR TITLE
More retries

### PR DESCRIPTION
**Pull request by thomasrockhu**
Inspired by https://github.com/nmoinvaz/codecov-python/commit/19f958fce8f34c06fa7dd7a1ebfbad216653041b with a little less infrastructure

Retry our API calls for a little more resiliency

### CODE REVIEW

**Comment by thomasrockhu** [comment]
cc: @nmoinvaz

**Comment by nmoinvaz** [comment]
Only part I am unsure of is the exception line:
except AssertionError:

It seems that perhaps that will only catch `assert` lines. But what if requests throws its own exception, ie: `except (requests.exceptions.RequestException, requests.urllib3.exceptions.HTTPError):`

**Comment by nmoinvaz** [comment]
Also would you be open to a PR that allows the number of retries to be configurable via command line arg?

**Comment by thomasrockhu** [comment]
@nmoinvaz I'll add a PR for the first issue, feel free to open one for the second

**Pull request merged**
