### PR TITLE
Fix missed single quotes in gcov command

### PR DESCRIPTION
**Pull request by AenBleidd**
Missed single quotes around *.gcno pattern lead to next error:

```
Executing gcov (['find', 'EXAMPLE_PATH', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+'])
Error running `['find', 'EXAMPLE_PATH', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+']`: Command '['find', 'EXAMPLE_PATH', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+']' returned non-zero exit status 1
```

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
@drazisil, could you please review this PR? It's a fix for a blocker we have. Thanks in advance

**Comment by AenBleidd** [comment]
@drazisil, @hootener, @thomasrockhu, ping

**Comment by drazisil** [comment]
@AenBleidd can you please rebase from master and we'll confirm checks pass?

**Comment by thomasrockhu** [comment]
@AenBleidd I rebased for you here, but want to double-check to make sure this is what you intended

**Comment by AenBleidd** [comment]
Since it doesn't use `find` command anymore, my changes are not needed. Sorry for the inconvenience

**Pull request closed without merging**
