### PR TITLE
Added ability to skip SSL verification with --no-verify flag.

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Rebased

**Comment by thomasrockhu** [comment]
@nmoinvaz, apologies remind me of the use case here?

**Comment by nmoinvaz** [comment]
@Dead2 do you remember why we added this?

**Comment by Dead2** [comment]
@nmoinvaz It was added because we wanted to proxy the upload through a third-party server, to see whether that fixed our (still-existing) issues with uploads from some CI jobs not working directly to codecov.io (1-4 in every CI run, even with 40+ retries spread over 4 hours).

**Comment by thomasrockhu** [comment]
@nmoinvaz, I'm likely going to close this out as I don't think this should exist in the uploader. @Dead2, would love your input here as well as I don't think this PR would have helped with the upload issues. More importantly, are you still running into those issues.

**Comment by nmoinvaz** [comment]
I'm ok with that. We have not had an upload issue in sometime.

**Pull request closed without merging**
