### PR TITLE
Appveyor support

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
Clean Appveyor build of this series are ongoing here: https://ci.appveyor.com/project/jayvdb/codecov-python/build/1.0.8
(I've had green Appveyor builds of this series, but they are using messy branches I have blown away)
Im happy to rework any of these PRs, if you've got problems with them, or suggestions for improvement.

**Comment by stevepeak** [comment]
Thank you for the PR! I've enabled AppVeyor for this repo on the Codecov organization lvl. I'll keep an eye on these builds. Cheers!

**Comment by jayvdb** [comment]
You'll also need to put the token in your Appveyor env vars due to https://github.com/codecov/codecov-python/issues/27 (a fix for that would be amazing?)

**Comment by stevepeak** [comment]
#27 is fixed. I'm assuming this PR will truncate #31 and #30. Let me know if that assumption is correct. Thanks!

**Comment by jayvdb** [comment]
I have no idea what github will do with #31 and #30 - hopefully it closes them automagically indicating they have been merged, but probably we'll need to close them manually.

I separated them originally as they are distinct and not dependant on each other, and #31 is higher priority as it is an externally facing 'bug', while the other two issues are internal only.

I do know that if you merged #30, then #31, and then #32 (possibly after a rebase), the commit log/tree will be cleaner due to less merges.  But just merging #32 will copy the complex commit dependencies/sequences into master's commit log/tree, which is also nice.

**Comment by jayvdb** [comment]
Build is green, but Github is still "Waiting for AppVeyor build to complete" ;-(

**Comment by jayvdb** [comment]
OK; my build is green (I dont have an envvar set), but your build isnt (no token problem).  That is interesting.
While you sort that out, could you merge/review #31 so I can use codecov-python on other projects without 2.6 builds breaking.

**Pull request merged**
