### PR TITLE
Use `cwd` with Popen instead of "cd X &&"

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/codecov/codecov-python/issues/139

Not tested.

### CODE REVIEW

**Comment by rth** [comment]
Appveyor is failing, I think, because the `root` path is escaped as though it was used in CLI while it's passed to subprocess.

https://github.com/rth/codecov-python/commit/6b7c5c13cfcb5c06dd57a73026537c190b051aa5 should fix it I think.

**Comment by blueyed** [comment]
> This PR does remove a call to try_to_run('git ls-files'), was that intentional?

Yes, since the correct dir should be used already.
But not sure, and it should also be done for `hg` then.

Using `-C` / `--cwd` is a good alternative.

I am going to close this PR for now.  It is not complete, and not really important I think.

**Comment by blueyed** [comment]
> This PR does remove a call to try_to_run('git ls-files'), was that intentional?

Yes, since the correct dir should be used already.  At least I guess that was the idea, but it might also be unintentional after all.
Either way, it should be the same for `hg` then probably.

Using `-C` / `--cwd` is a good alternative.

**Comment by blueyed** [comment]
> This PR does remove a call to try_to_run('git ls-files'), was that intentional?

Yes, since the correct dir should be used already.  At least I guess that was the idea, but it might also be unintentional after all.
Either way, it should be the same for `hg` then probably.

Using `-C` / `--cwd` is a good alternative indeed.

**Comment by blueyed** [comment]
> This PR does remove a call to try_to_run('git ls-files'), was that intentional?

Yes, since the correct dir should be used already.  At least I guess that was the idea, but it might also be unintentional after all.
Either way, it should be the same for `hg` then probably.

Using `-C` / `--cwd` is a good alternative indeed.

**Comment by thomasrockhu** [comment]
@blueyed is this already fixed via https://github.com/codecov/codecov-python/pull/234?

**Comment by blueyed** [comment]
@thomasrockhu 
Yes: https://github.com/codecov/codecov-python/pull/234/files#diff-ed4cb86e1f4a5c5feeecc37b90ec6a23R623-R626, closing.

**Pull request closed without merging**
