### PR TITLE
Fixed find command not working on Windows.

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by raczben** [comment]
Why this fix has not been accepted?

**Comment by nmoinvaz** [comment]
@raczben you can use my fork which has the fixes if you want.

**Comment by raczben** [comment]
No, I just hoped... My issue is https://stackoverflow.com/q/59934305/2506522

**Comment by drazisil** [comment]
@nmoinvaz Can you hunt down and correct the error with the changed method name? If not, I can, but I have several other issues on my plate, so I can't gave a timeline.

**Comment by nmoinvaz** [comment]
What is the error?

**Comment by nmoinvaz** [comment]
Looks like that is the case.. I will rebase.

**Comment by drazisil** [comment]
@nmoinvaz Thanks! Will cut a new release in a few, I'm fixing an issue where the version is wrong.

**Pull request merged**
