### PR TITLE
Use coverage<4 on 3.0–3.2, as 4 drops support

### PR DESCRIPTION
**Pull request by gsnedders**
PyPy3 is still at 3.2, and that's part of the test matrix here, so we ought to make sure we still work there.

### CODE REVIEW

**Comment by gsnedders** [comment]
(Sorry for rather digressing and trying to fix all the CI failures while I was at it!)

**Comment by gsnedders** [comment]
Uh, why is it reporting code coverage down v. 9cee68cd1b630397e443dcb7849574a38dca484a? b396aa6265c5bafce40b0dc50ac1b54103177a28 is the latest build on master—is that ignored because of CI failing?

**Comment by stevepeak** [comment]
Hey @gsnedders thank you for the PR! Very nice job :+1: 

Actually `9cee68c` passed CI tests but failed in my custom test suite, which was expected as I need to clean it up with recent changes.

Everything here looks good to me. Ready for a merge and deploy?

**Comment by gsnedders** [comment]
@stevepeak Yup, unless you want me to rebase it to squash the fixup commits first.

**Comment by stevepeak** [comment]
Hey @gsnedders I'm getting a strange error when trying to upload the new version. Do you know how to fix this?

```
python setup.py sdist bdist_wheel upload
error in codecov setup command: Invalid environment marker: python_version>="3.0" and python_version<"3.3"
```

**Comment by gsnedders** [comment]
@stevepeak Too old a version of setuptools (so a `pip install -U setuptools` would fix that). I'm surprised you're hitting that given you already had `futures` dependent on Python version, though!

**Comment by stevepeak** [comment]
Thank you! That worked and deployed :)

**Comment by stevepeak** [comment]
I'm seeing errors on builds like these: https://travis-ci.org/codecov/example-go/builds/98126571

They likely have out-of-date `setuptools` since that fixed my issue.

**Comment by gsnedders** [comment]
Did you revert this?

**Comment by stevepeak** [comment]
I had to unfortunately. Many customers not using Python still use this uploaded. I found quickly that the same setup tools issue I experienced locally was occurring in most CI providers. 

I'll be back to work on this in a week, for now customers must install the required version of coverage they prefer before installing Codecov.

My apologies for not reporting this earlier here, I've been back logged on some items that I'm working through. Thanks!

**Pull request merged**
