### PR TITLE
Add Azure Pipelines support

### PR DESCRIPTION
**Pull request by thijsmie**
This commit adds Azure Pipeline support using exactly the same configuration as the codecov bash script uses.

### CODE REVIEW

**Comment by thijsmie** [comment]
Can I get an update on this PR?

**Comment by nmoinvaz** [comment]
I think this PR needs unit tests added. See my PR here for an example:
https://github.com/codecov/codecov-python/pull/265

**Comment by thijsmie** [comment]
Hi @nmoinvaz, I'd be happy to write a test case but I am afraid it would be a wasted effort with no maintainer activity since somewhere halfway April.

**Comment by mensinda** [comment]
+1 for getting this merged. I am currently using these changes to get https://github.com/mesonbuild/meson/pull/8894 going.

**Comment by thijsmie** [comment]
Clearly @codecov-devops doesn't care about getting contributions to this project, as they have not deemed to even give any response at all, positive or negative.

**Pull request closed without merging**
