### PR TITLE
Fix command line quoting for Windows

### PR DESCRIPTION
**Pull request by ofek**
cc @stevepeak Single quotes do not work in `cmd`, only `powershell`:

https://ci.appveyor.com/project/Datadog/integrations-core/builds/19797599#L705

capture

Without `git ls-files` results, path combining does not work cross-platform

### CODE REVIEW

**Comment by ofek** [comment]
cc @thomasrockhu 😄

**Comment by ofek** [comment]
@thomasrockhu Can we merge?

**Comment by nmoinvaz** [comment]
Please merge this change.

**Comment by ofek** [comment]
cc @drazisil

**Comment by drazisil** [comment]
@ofek

I'm out sick for now, i will take a look when i get back, thanks for the ping.

**Comment by ofek** [comment]
No worries, get well!

**Comment by ofek** [comment]
Any update?

**Comment by thomasrockhu** [comment]
This will be added to the next release cc: @drazisil

**Comment by ofek** [comment]
Thank you!!!

**Pull request merged**
