### PR TITLE
[WIP] Add gcov-source-match option

### PR DESCRIPTION
**Pull request by sublimator**
Just opening this up for discussion. This is the quick hack I made to `get on with it`. gcov files have a `:Source:` field, and this adds facility for filtering by source with a regular expression, via a `--gcov-source-match` option.

Some of the issues:
- The read() function logs the files, making it seem like they are always included in the report 
- This is applied to the reports list made after all the gcov files have been read

### CODE REVIEW

**Comment by sublimator** [comment]
bump, any ideas ?

**Comment by stevepeak** [comment]
Hey @sublimator the CI failure is due to a backend change. A rebase should clean it up.

The read() function: I agree with what you say. I've made this commit (c9627cb2681982f03fa808125e74282d5f6f76ad) to only print when actually included (and not failed).

Thank you!

**Comment by stevepeak** [comment]
@sublimator which repo can I test this on? Thanks!

**Comment by vheon** [comment]
@stevepeak I would actually love this feature for https://github.com/Valloric/ycmd. Right now I've used the `--gcov-glob` to exclude the tests and some of the Boost libraries that we have embedded into the repo, but  for the `.hpp` files that we actually import in our code there is not way to exclude them while with this option we could (https://codecov.io/gh/vheon/ycmd/tree/coverage-c%2B%2B/cpp/BoostParts/boost).

**Comment by stevepeak** [comment]
@vheon did you give this PR a shot? Did it work out for you?

**Comment by thomasrockhu** [comment]
Going to close this out due to the age of the PR.  Let me know if we should revisit

**Pull request closed without merging**
