### PR TITLE
Added support for gzipping reports.

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by nmoinvaz** [comment]
See #161.

**Comment by nmoinvaz** [comment]
This could help with network connectivity issues because sometimes the gcov blob is large.

**Comment by nmoinvaz** [comment]
@drazisil any possibility for merging this one too?

**Comment by drazisil** [comment]
@nmoinvaz Not sure how server side would handle this. @ThiagoCodecov do you know if this would cause issues?

**Comment by nmoinvaz** [comment]
It is something I believe the [bash](https://codecov.io/bash) uploader already supports: `say "${e}==>${x} Gzipping contents"`.

**Comment by drazisil** [comment]
@nmoinvaz Good observation. (keeping track of so many uploaders is a pain when they don't have feature parity)

**Pull request merged**
