### PR TITLE
Include the cacert in the PUT call when uploading to S3

### PR DESCRIPTION
**Pull request by jsiirola**
This PR adds a `verify=codecov.cacert` argument to the `put()` call when uploading results to S3.  This resolves a problem where a user-specified CACert file is required to successfully connect to the codecov server.  The initial connection to codecov ('Pinging codecov...') includes the CACert and is successful, but the subsequent upload fails because the CACert was not included.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
@thomasrockhu I can create a new PR for this issue with conflicts resolved if you would like.

**Comment by thomasrockhu** [comment]
@nmoinvaz yes please, or resolve conflicts, your choice

**Comment by nmoinvaz** [comment]
I don't have the ability to edit the PR so I created #266 based on updated commit.

**Comment by thomasrockhu** [comment]
Closed via https://github.com/codecov/codecov-python/pull/266

**Pull request closed without merging**
